# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [ ]:
import numpy as np

arr1=np.random.randint(1,20,size=(5,5))
print(f"original array :",arr1)

arr1[: ,2]=1  #[row,column]
print(f"new array:",arr1)
















# import numpy as np

# # Create a NumPy array of shape (5, 5) filled with random integers
# array = np.random.randint(1, 21, size=(5, 5))
# print("Original array:")
# print(array)

# # Replace all the elements in the third column with 1
# array[:, 2] = 1
# print("Modified array:")
# print(array)

original array : [[11  7  3 11  8]
 [ 2  6  2  6 16]
 [ 5  3  4 15 19]
 [ 4  1  1 15  5]
 [19 10  1 19 14]]
new array: [[11  7  1 11  8]
 [ 2  6  1  6 16]
 [ 5  3  1 15 19]
 [ 4  1  1 15  5]
 [19 10  1 19 14]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [8]:
arr2=np.random.randint(1,16,size=(4,4))
print("original array:")
print(arr2)

np.fill_diagonal(arr2,0)
print("modified array:")
print(arr2)















# # Create a NumPy array of shape (4, 4) with values from 1 to 16
# array = np.arange(1, 17).reshape((4, 4))
# print("Original array:")
# print(array)

# # Replace the diagonal elements with 0
# np.fill_diagonal(array, 0)
# print("Modified array:")
# print(array)

original array:
[[ 5 13 14 12]
 [ 2 12  1  1]
 [ 6  7 11  8]
 [ 6 15  2 13]]
modified array:
[[ 0 13 14 12]
 [ 2  0  1  1]
 [ 6  7  0  8]
 [ 6 15  2  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [11]:
arr3=np.random.randint(1,37,size=(6,6))
print("original array:")
print(arr3)

arr4=arr3[2:5,1:4]
print("Extracted array:")
print(arr4)












# # Create a NumPy array of shape (6, 6) with values from 1 to 36
# array = np.arange(1, 37).reshape((6, 6))
# print("Original array:")
# print(array)

# # Extract the sub-array
# sub_array = array[2:5, 1:4]
# print("Sub-array:")
# print(sub_array)

original array:
[[26  7 26 11 27 12]
 [26  8  9 16  7  6]
 [ 6 24 15 23 36 17]
 [22  1  8 21  2 15]
 [ 1 30  5  6 36 10]
 [27 20 25 13 16  8]]
Extracted array:
[[24 15 23]
 [ 1  8 21]
 [30  5  6]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
arr5=np.random.randint(1,37,size=(5,5))
print("original array:")
print(arr5)


print("modify array")
border=np.copy(arr5)
border[1:4,1:4]=0
print(border)














# # Create a NumPy array of shape (5, 5) with random integers
# array = np.random.randint(1, 21, size=(5, 5))
# print("Original array:")
# print(array)

# # Extract the elements on the border
# border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
# print("Border elements:")
# print(border_elements)

original array:
[[12 17 22  9 16]
 [26 27 23 28 11]
 [27 22 33 22 30]
 [ 5 24  4 15 34]
 [22 11  6 27 21]]
modify array
[[12 17 22  9 16]
 [26  0  0  0 11]
 [27  0  0  0 30]
 [ 5  0  0  0 34]
 [22 11  6 27 21]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [23]:
arr6=np.random.randint(1,100,size=(3,4))
arr7=np.random.randint(1,100,size=(3,4))

print("first array:")
print(arr6)
print("second array:")
print(arr7)

print("Element-wise Addition:")
print(arr6+arr7)

print("Element-wise Subtraction:")
print(arr6-arr7)

print("Element-wise Multiplication:")
print(arr6*arr7)

print("Element-wise Division:")
print(arr6/arr7)

























# # Create two NumPy arrays of shape (3, 4) filled with random integers
# array1 = np.random.randint(1, 11, size=(3, 4))
# array2 = np.random.randint(1, 11, size=(3, 4))
# print("Array 1:")
# print(array1)
# print("Array 2:")
# print(array2)

# # Perform element-wise operations
# addition = array1 + array2
# subtraction = array1 - array2
# multiplication = array1 * array2
# division = array1 / array2

# print("Element-wise addition:")
# print(addition)
# print("Element-wise subtraction:")
# print(subtraction)
# print("Element-wise multiplication:")
# print(multiplication)
# print("Element-wise division:")
# print(division)

first array:
[[99 94 82 57]
 [28 94 13 37]
 [64 89 92 79]]
second array:
[[75  4  4 45]
 [39 54 59 20]
 [74 79 46  8]]
Element-wise Addition:
[[174  98  86 102]
 [ 67 148  72  57]
 [138 168 138  87]]
Element-wise Subtraction:
[[ 24  90  78  12]
 [-11  40 -46  17]
 [-10  10  46  71]]
Element-wise Multiplication:
[[7425  376  328 2565]
 [1092 5076  767  740]
 [4736 7031 4232  632]]
Element-wise Division:
[[ 1.32       23.5        20.5         1.26666667]
 [ 0.71794872  1.74074074  0.22033898  1.85      ]
 [ 0.86486486  1.12658228  2.          9.875     ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [26]:
arr7=np.random.randint(1,17,size=(4,4))
print("original Array:")
print(arr7)

row=np.sum(arr7,axis=1)
cols=np.sum(arr7,axis=0)

print("Row-wise Sum")
print(row)

print("Column-wise Sum")
print(cols)


















# # Create a NumPy array of shape (4, 4) with values from 1 to 16
# array = np.arange(1, 17).reshape((4, 4))
# print("Original array:")
# print(array)

# # Compute the row-wise and column-wise sum
# row_sum = np.sum(array, axis=1)
# column_sum = np.sum(array, axis=0)

# print("Row-wise sum:")
# print(row_sum)
# print("Column-wise sum:")
# print(column_sum)

original Array:
[[ 2  2 15  1]
 [ 8  8 16  7]
 [11  6  2 12]
 [ 9 13  2 14]]
Row-wise Sum
[20 39 31 38]
Column-wise Sum
[30 29 35 34]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [32]:

arr8=np.random.randint(1,100,size=(5,5))
print("original Array:")
print(arr8)

print("Mean of the array:",np.mean(arr8))
print("Median of the array:",np.median(arr8))
print("Standard Deviation of the array:",np.std(arr8))
print("Variance of the array:",np.var(arr8))



















# # Create a NumPy array of shape (5, 5) filled with random integers
# array = np.random.randint(1, 21, size=(5, 5))
# print("Original array:")
# print(array)

# # Compute the statistical values
# mean = np.mean(array)
# median = np.median(array)
# std_dev = np.std(array)
# variance = np.var(array)

# print("Mean:", mean)
# print("Median:", median)
# print("Standard Deviation:", std_dev)
# print("Variance:", variance)

original Array:
[[ 1  2  2 32  1]
 [49 37 47 13 55]
 [54 11 62 26 19]
 [36 89 51 41  4]
 [70 35 85 78 12]]
Mean of the array: 36.48
Median of the array: 36.0
Standard Deviation of the array: 26.79420832941328
Variance of the array: 717.9296


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [34]:
arr9=np.random.randint(1,10,size=(3,3))
print("original Array:")
print(arr9)

#normalized= x-mean/std

mean=np.mean(arr9)
std=np.std(arr9)

print("Normalized Array:")
print((arr9-mean)/std)



















# # Create a NumPy array of shape (3, 3) with values from 1 to 9
# array = np.arange(1, 10).reshape((3, 3))
# print("Original array:")
# print(array)

# # Normalize the array
# mean = np.mean(array)
# std_dev = np.std(array)
# normalized_array = (array - mean) / std_dev

# print("Normalized array:")
# print(normalized_array)

original Array:
[[7 3 2]
 [9 6 9]
 [1 7 7]]
Normalized Array:
[[ 0.47809144 -0.95618289 -1.31475147]
 [ 1.19522861  0.11952286  1.19522861]
 [-1.67332005  0.47809144  0.47809144]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
# Create a NumPy array of shape (3, 3) filled with random integers
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array:")
print(result)

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [ ]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [ ]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)